---
apiVersion: v1
kind: Service
metadata:
    name: hollowapp
    labels:
        app: hollowapp
spec:
    type: ClusterIP
    ports:
    - port: 5000
      protocol: TCP
      targetPort: 5000
      selector:
        app: hollowapp
        metadata:
            name: hollowapp
            labels:
                app: hollowapp
spec:
    rules:
    - host: hollowapp.hollow.local
      http:
      paths:
      - path: /
        backend:
        serviceName: hollowapp
        servicePort: 5000
